namespace PlayGroundSharp.App;

internal static class AppLocalization
{
    private static readonly IReadOnlyDictionary<string, string> Japanese = new Dictionary<string, string>
    {
        ["Ui.AppSubtitle"] = "C# 対話コンソール",
        ["Ui.Types"] = "型",
        ["Ui.Session"] = "セッション",
        ["Ui.Stop"] = "停止",
        ["Ui.Restart"] = "再起動",
        ["Ui.Reset"] = "リセット",
        ["Ui.Clear"] = "クリア",
        ["Ui.Inspect"] = "詳細",
        ["Tooltip.Types"] = "シンボル エクスプローラーを開閉します",
        ["Tooltip.Session"] = "変数・NuGet・ライブラリ・using・設定を開閉します",
        ["Tooltip.Stop"] = "実行中のコードを停止します。応答しない場合はWorkerを再起動します",
        ["Tooltip.Restart"] = "Workerを再起動します。セッション内の変数・型・メソッドは失われます",
        ["Tooltip.Reset"] = "Submission状態をリセットします。追加した参照とusingは維持されます",
        ["Tooltip.Clear"] = "画面上のTranscriptだけをクリアします。セッション状態は維持されます",
        ["Menu.File"] = "ファイル",
        ["Menu.Edit"] = "編集",
        ["Menu.Data"] = "データ",
        ["Menu.View"] = "表示",
        ["Menu.Help"] = "ヘルプ",
        ["Menu.SaveWorkspace"] = "ワークスペースを保存…",
        ["Menu.OpenWorkspace"] = "ワークスペースを開く…",
        ["Menu.Exit"] = "終了",
        ["Menu.FocusInput"] = "入力欄へ移動",
        ["Menu.ClearTranscript"] = "Transcriptをクリア",
        ["Menu.InspectFile"] = "ファイル情報を挿入…",
        ["Menu.PreviewText"] = "テキストプレビューを挿入…",
        ["Menu.ReadLines"] = "行ストリームを挿入…",
        ["Menu.ReadJsonArray"] = "JSON配列の読み込みを挿入…",
        ["Menu.ReadJsonLines"] = "JSON Linesの読み込みを挿入…",
        ["Menu.SymbolExplorer"] = "シンボル エクスプローラー",
        ["Menu.Workspace"] = "ワークスペース パネル",
        ["Menu.OpenHelp"] = "PlayGroundSharp ヘルプ",
        ["Menu.About"] = "PlayGroundSharpについて",
        ["Explorer.Title"] = "シンボル エクスプローラー",
        ["Explorer.Subtitle"] = "名前空間・型・メソッド",
        ["Explorer.Filter"] = "シンボルを検索…",
        ["Explorer.FilterTooltip"] = "名前空間、型、メソッド、コメント、アセンブリで検索",
        ["Explorer.Empty"] = "一致するシンボルがありません",
        ["Explorer.EmptyHint"] = "別の名前空間、型、メソッド名を試してください。",
        ["Docs.Summary"] = "概要",
        ["Docs.Parameters"] = "パラメーター",
        ["Docs.Returns"] = "戻り値",
        ["Docs.OpenJapanese"] = "Microsoft Learn 日本語版を開く",
        ["Docs.HoverHint"] = "クリックすると詳細を固定表示します",
        ["Workspace.Title"] = "ワークスペース",
        ["Workspace.Subtitle"] = "セッション状態と依存関係",
        ["Tab.Variables"] = "変数",
        ["Tab.NuGet"] = "NuGet",
        ["Tab.Libraries"] = "ライブラリ",
        ["Tab.Usings"] = "using",
        ["Tab.Settings"] = "設定",
        ["Column.Kind"] = "種類",
        ["Column.Name"] = "名前",
        ["Column.Type"] = "型",
        ["Column.Value"] = "値",
        ["Column.Version"] = "バージョン",
        ["Column.Source"] = "ソース",
        ["Variables.Empty"] = "変数はまだありません",
        ["Variables.EmptyHint"] = "変数を宣言するとここに表示されます。",
        ["NuGet.SearchTooltip"] = "パッケージID、タイトル、説明、タグ",
        ["NuGet.Search"] = "検索",
        ["NuGet.IncludePrerelease"] = "プレリリースを含める",
        ["NuGet.Verified"] = "  認証済み",
        ["NuGet.Install"] = "追加",
        ["NuGet.DownloadsSuffix"] = " ダウンロード",
        ["Libraries.Empty"] = "追加済みライブラリはありません",
        ["Libraries.EmptyHint"] = "パッケージまたはDLLを追加してください。",
        ["Settings.ExecutionKey"] = "実行キー",
        ["Settings.Theme"] = "テーマ",
        ["Settings.Language"] = "表示言語",
        ["Settings.Security"] = "任意のC#コードは現在のWindowsユーザー権限で実行されます。",
        ["Inspector.Title"] = "結果インスペクター",
        ["Inspector.Snapshot"] = "Workerで取得したスナップショット",
        ["Status.StartingWorker"] = "Workerを起動中",
        ["Status.WorkerDisconnected"] = "Worker未接続",
        ["Status.Ready"] = "準備完了",
        ["Status.Compiling"] = "コンパイル中",
        ["Status.Cancelling"] = "停止中",
        ["Status.Running"] = "実行中",
        ["Status.RestoringPackage"] = "パッケージを復元中",
        ["Status.SearchingPackages"] = "パッケージを検索中",
        ["Status.PackageSearchFailed"] = "パッケージ検索に失敗",
        ["Status.PackageInstallFailed"] = "パッケージ追加に失敗",
        ["Status.Completions"] = "{0} 件の候補",
        ["Status.AddedUsing"] = "using {0} を追加しました",
        ["Status.UsingFailed"] = "usingの追加に失敗",
        ["Status.SavingWorkspace"] = "ワークスペースを保存中",
        ["Status.LoadingWorkspace"] = "ワークスペースを読み込み中",
        ["Status.ReplayingWorkspace"] = "ワークスペースを再生中 ({0}/{1})",
        ["Status.WorkspaceLoaded"] = "ワークスペースを読み込みました",
        ["Status.WorkspaceLoadFailed"] = "ワークスペースの読み込みに失敗",
        ["Session.Count"] = "{0} 件のSubmission",
        ["Session.Memory"] = "{0} 件のSubmission — Worker {1:N0} MiB",
        ["Session.StateLost"] = "0 件のSubmission — Worker状態を消失",
        ["Session.Restarted"] = "0 件のSubmission — Worker再起動済み",
        ["Diagnostics.Count"] = "エラー {0}、警告 {1}",
        ["Cursor.Position"] = "{0} 行、{1} 列",
        ["Explorer.Loading"] = "読み込み中…",
        ["Explorer.Unavailable"] = "Explorerを利用できません",
        ["Explorer.Count"] = "型 {0:N0} · メソッド {1:N0}",
        ["Explorer.Matches"] = "{0:N0} 件一致",
        ["Package.SearchPrompt"] = "nuget.orgからパッケージを検索",
        ["Package.Searching"] = "nuget.orgを検索中…",
        ["Package.NoneFound"] = "パッケージが見つかりません。",
        ["Package.Found"] = "{0:N0} 件中 {1} 件を表示",
        ["Package.Installing"] = "{0} {1} を追加中…",
        ["Package.LatestStable"] = "最新安定版",
        ["Package.Installed"] = "{0} を追加しました。",
        ["Package.InstalledVersion"] = "{0} {1} を追加しました。",
        ["Package.AlreadyInstalled"] = "{0} {1} は追加済みです。",
        ["Assist.CompletionHint"] = "Tab: 補完  ↑↓: 選択  Esc: 閉じる",
        ["Assist.SignatureHint"] = "{0} オーバーロード · 第{1}引数 · ↑↓: 切替",
        ["Assist.Documentation"] = "ドキュメント",
        ["Assist.LoadingDocumentation"] = "ドキュメントを読み込み中…",
        ["Assist.NoDocumentation"] = "この候補のドキュメントはありません。",
        ["Assist.DocumentationLanguageHint"] = "参照ライブラリに付属する原文を表示します。日本語版はシンボル エクスプローラーからMicrosoft Learnを開けます。",
        ["Message.WorkerConnected"] = "Workerへ接続しました。信頼できないコードやパッケージを実行しないでください。",
        ["Message.ExecutionCancelled"] = "実行を停止しました。",
        ["Message.SessionReset"] = "セッションをリセットしました。",
        ["Message.WorkerRestarted"] = "Workerを再起動しました。変数とメソッドは失われ、参照とusingは復元されました。",
        ["Message.ForcedRestart"] = "停止できないためWorkerを強制終了しました。Transcriptと入力履歴は保持されましたが、セッション変数は失われました。",
        ["Message.PackageAdded"] = "パッケージを追加しました: {0} {1}",
        ["Message.UsingAdded"] = "usingを追加しました: {0}",
        ["Message.UsingActive"] = "usingは追加済みです: {0}",
        ["Message.ReferenceAdded"] = "参照を追加しました: {0}",
        ["Message.NoReferences"] = "動的参照はありません。",
        ["Message.NoPackages"] = "パッケージはありません。",
        ["Message.UnknownCommand"] = "不明なコマンド: {0}",
        ["Message.WorkspaceSaved"] = "ワークスペースを保存しました: {0}",
        ["Message.WorkspaceLoaded"] = "ワークスペースを読み込み、{0}件のSubmissionを再生しました。",
        ["Message.ReferenceMissing"] = "参照ファイルが見つからないためスキップしました: {0}",
        ["Message.ReplayFailed"] = "Submission {0} の再生に失敗しました。",
        ["Dialog.WorkspaceLoadTitle"] = "ワークスペースを開く",
        ["Dialog.WorkspaceLoadWarning"] = "現在のWorker状態を破棄し、保存済みSubmissionを順番に再実行します。ファイル操作などの副作用も再実行されます。続行しますか？",
        ["Dialog.ErrorTitle"] = "PlayGroundSharp エラー",
        ["Dialog.WorkspaceFilter"] = "PlayGroundSharp ワークスペース (*.pgsworkspace)|*.pgsworkspace|JSON (*.json)|*.json",
        ["Dialog.DataFileFilter"] = "すべてのファイル (*.*)|*.*|JSON (*.json;*.jsonl)|*.json;*.jsonl|テキスト (*.txt;*.log;*.csv)|*.txt;*.log;*.csv",
        ["Help.Title"] = "PlayGroundSharp ヘルプ",
        ["Help.SecurityTitle"] = "セキュリティ上の注意",
        ["Help.SecurityMessage"] = "入力したC#コードと追加したパッケージは、現在のWindowsユーザー権限で実行されます。信頼できないコードやパッケージを実行しないでください。",
        ["About.Message"] = "状態保持型C#対話コンソール\n.NET 10 / WPF / Roslyn\n\n任意のコードは現在のWindowsユーザー権限で実行されます。",
        ["Completion.Command"] = "PlayGroundSharp コマンド",
        ["Completion.Namespace"] = "追加済みアセンブリの名前空間です。Tabでusingコマンドを挿入します。"
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["Ui.AppSubtitle"] = "C# interactive console", ["Ui.Types"] = "Types", ["Ui.Session"] = "Session",
        ["Ui.Stop"] = "Stop", ["Ui.Restart"] = "Restart", ["Ui.Reset"] = "Reset", ["Ui.Clear"] = "Clear", ["Ui.Inspect"] = "Inspect",
        ["Tooltip.Types"] = "Toggle the Symbol Explorer",
        ["Tooltip.Session"] = "Toggle variables, NuGet, libraries, usings, and settings",
        ["Tooltip.Stop"] = "Stop running code; restart the Worker if it does not respond",
        ["Tooltip.Restart"] = "Restart the Worker; session variables, types, and methods are lost",
        ["Tooltip.Reset"] = "Reset submission state while keeping added references and usings",
        ["Tooltip.Clear"] = "Clear only the visible transcript; session state is preserved",
        ["Menu.File"] = "File", ["Menu.Edit"] = "Edit", ["Menu.Data"] = "Data", ["Menu.View"] = "View", ["Menu.Help"] = "Help",
        ["Menu.SaveWorkspace"] = "Save Workspace…", ["Menu.OpenWorkspace"] = "Open Workspace…", ["Menu.Exit"] = "Exit",
        ["Menu.FocusInput"] = "Focus Input", ["Menu.ClearTranscript"] = "Clear Transcript",
        ["Menu.InspectFile"] = "Insert File Info…", ["Menu.PreviewText"] = "Insert Text Preview…",
        ["Menu.ReadLines"] = "Insert Line Stream…", ["Menu.ReadJsonArray"] = "Insert JSON Array Reader…",
        ["Menu.ReadJsonLines"] = "Insert JSON Lines Reader…", ["Menu.SymbolExplorer"] = "Symbol Explorer",
        ["Menu.Workspace"] = "Workspace Panel", ["Menu.OpenHelp"] = "PlayGroundSharp Help", ["Menu.About"] = "About PlayGroundSharp",
        ["Explorer.Title"] = "Symbol Explorer", ["Explorer.Subtitle"] = "Namespaces, types and methods",
        ["Explorer.Filter"] = "Filter symbols…", ["Explorer.FilterTooltip"] = "Filter by namespace, type, method, documentation or assembly",
        ["Explorer.Empty"] = "No matching symbols", ["Explorer.EmptyHint"] = "Try another namespace, type or method name.",
        ["Docs.Summary"] = "Summary", ["Docs.Parameters"] = "Parameters", ["Docs.Returns"] = "Returns",
        ["Docs.OpenJapanese"] = "Open Microsoft Learn", ["Docs.HoverHint"] = "Click to pin details",
        ["Workspace.Title"] = "Workspace", ["Workspace.Subtitle"] = "Session state and dependencies",
        ["Tab.Variables"] = "Variables", ["Tab.NuGet"] = "NuGet", ["Tab.Libraries"] = "Libraries", ["Tab.Usings"] = "Usings", ["Tab.Settings"] = "Settings",
        ["Column.Kind"] = "Kind", ["Column.Name"] = "Name", ["Column.Type"] = "Type", ["Column.Value"] = "Value", ["Column.Version"] = "Version", ["Column.Source"] = "Source",
        ["Variables.Empty"] = "No variables yet", ["Variables.EmptyHint"] = "Run a declaration to populate this view.",
        ["NuGet.SearchTooltip"] = "Package ID, title, description or tag", ["NuGet.Search"] = "Search", ["NuGet.IncludePrerelease"] = "Include prerelease",
        ["NuGet.Verified"] = "  Verified", ["NuGet.Install"] = "Install", ["NuGet.DownloadsSuffix"] = " downloads",
        ["Libraries.Empty"] = "No imported libraries", ["Libraries.EmptyHint"] = "Install a package or add a DLL.",
        ["Settings.ExecutionKey"] = "Execution key", ["Settings.Theme"] = "Theme", ["Settings.Language"] = "Language",
        ["Settings.Security"] = "Arbitrary C# runs with your Windows user permissions.",
        ["Inspector.Title"] = "Result Inspector", ["Inspector.Snapshot"] = "Snapshot captured in Worker",
        ["Status.StartingWorker"] = "Starting Worker", ["Status.WorkerDisconnected"] = "Worker disconnected", ["Status.Ready"] = "Ready",
        ["Status.Compiling"] = "Compiling", ["Status.Cancelling"] = "Cancelling", ["Status.Running"] = "Running",
        ["Status.RestoringPackage"] = "Restoring package", ["Status.SearchingPackages"] = "Searching packages",
        ["Status.PackageSearchFailed"] = "Package search failed", ["Status.PackageInstallFailed"] = "Package install failed",
        ["Status.Completions"] = "{0} completions", ["Status.AddedUsing"] = "Added using {0}", ["Status.UsingFailed"] = "Using import failed",
        ["Status.SavingWorkspace"] = "Saving workspace", ["Status.LoadingWorkspace"] = "Loading workspace",
        ["Status.ReplayingWorkspace"] = "Replaying workspace ({0}/{1})", ["Status.WorkspaceLoaded"] = "Workspace loaded",
        ["Status.WorkspaceLoadFailed"] = "Workspace load failed",
        ["Session.Count"] = "{0} submissions", ["Session.Memory"] = "{0} submissions — Worker {1:N0} MiB",
        ["Session.StateLost"] = "0 submissions — Worker state lost", ["Session.Restarted"] = "0 submissions — Worker restarted",
        ["Diagnostics.Count"] = "{0} errors, {1} warnings", ["Cursor.Position"] = "Ln {0}, Col {1}",
        ["Explorer.Loading"] = "Loading…", ["Explorer.Unavailable"] = "Explorer unavailable",
        ["Explorer.Count"] = "{0:N0} types · {1:N0} methods", ["Explorer.Matches"] = "{0:N0} matches",
        ["Package.SearchPrompt"] = "Search packages on nuget.org", ["Package.Searching"] = "Searching nuget.org…",
        ["Package.NoneFound"] = "No packages found.", ["Package.Found"] = "{0:N0} packages found — showing {1}",
        ["Package.Installing"] = "Installing {0} {1}…", ["Package.LatestStable"] = "latest stable",
        ["Package.Installed"] = "Installed {0}.", ["Package.InstalledVersion"] = "Installed {0} {1}.",
        ["Package.AlreadyInstalled"] = "{0} {1} is already installed.",
        ["Assist.CompletionHint"] = "Tab: complete  ↑↓: select  Esc: close",
        ["Assist.SignatureHint"] = "{0} overload(s) · parameter {1} · ↑↓: switch",
        ["Assist.Documentation"] = "Documentation",
        ["Assist.LoadingDocumentation"] = "Loading documentation…",
        ["Assist.NoDocumentation"] = "No documentation is available for this item.",
        ["Assist.DocumentationLanguageHint"] = "Shows documentation authored by the referenced library. Open localized Microsoft Learn from Symbol Explorer when available.",
        ["Message.WorkerConnected"] = "Worker connected. Do not execute untrusted code or packages.",
        ["Message.ExecutionCancelled"] = "Execution cancelled.", ["Message.SessionReset"] = "Session reset.",
        ["Message.WorkerRestarted"] = "Worker restarted. Variables and methods were lost; references and usings were restored.",
        ["Message.ForcedRestart"] = "Worker was terminated because cancellation did not complete. Session variables were lost; transcript and input history were preserved.",
        ["Message.PackageAdded"] = "Package added: {0} {1}", ["Message.UsingAdded"] = "Using added: {0}",
        ["Message.UsingActive"] = "Using already active: {0}", ["Message.ReferenceAdded"] = "Reference added: {0}",
        ["Message.NoReferences"] = "No dynamic references.", ["Message.NoPackages"] = "No packages.",
        ["Message.UnknownCommand"] = "Unknown command: {0}",
        ["Message.WorkspaceSaved"] = "Workspace saved: {0}", ["Message.WorkspaceLoaded"] = "Workspace loaded and {0} submissions replayed.",
        ["Message.ReferenceMissing"] = "Reference file was not found and was skipped: {0}", ["Message.ReplayFailed"] = "Submission {0} failed during replay.",
        ["Dialog.WorkspaceLoadTitle"] = "Open Workspace",
        ["Dialog.WorkspaceLoadWarning"] = "The current Worker state will be discarded and saved submissions replayed in order. Side effects such as file operations will run again. Continue?",
        ["Dialog.ErrorTitle"] = "PlayGroundSharp Error",
        ["Dialog.WorkspaceFilter"] = "PlayGroundSharp Workspace (*.pgsworkspace)|*.pgsworkspace|JSON (*.json)|*.json",
        ["Dialog.DataFileFilter"] = "All files (*.*)|*.*|JSON (*.json;*.jsonl)|*.json;*.jsonl|Text (*.txt;*.log;*.csv)|*.txt;*.log;*.csv",
        ["Help.Title"] = "PlayGroundSharp Help", ["Help.SecurityTitle"] = "Security notice",
        ["Help.SecurityMessage"] = "Submitted C# and added packages run with your current Windows user permissions. Do not run untrusted code or packages.",
        ["About.Message"] = "Stateful C# interactive console\n.NET 10 / WPF / Roslyn\n\nArbitrary code runs with your current Windows user permissions.",
        ["Completion.Command"] = "PlayGroundSharp command",
        ["Completion.Namespace"] = "Namespace from an added assembly; Tab inserts the using command."
    };

    public static IReadOnlyDictionary<string, string> Resources(AppLanguageMode mode) =>
        mode == AppLanguageMode.Japanese ? Japanese : English;

    public static string Text(AppLanguageMode mode, string key, params object?[] arguments)
    {
        var value = Resources(mode).GetValueOrDefault(key) ?? key;
        return arguments.Length == 0 ? value : string.Format(value, arguments);
    }
}
