namespace PlayGroundSharp.App;

internal static class AppLocalization
{
    private static readonly IReadOnlyDictionary<string, string> Japanese = new Dictionary<string, string>
    {
        ["Ui.AppSubtitle"] = "C# 対話コンソール",
        ["Ui.Types"] = "型",
        ["Ui.Session"] = "セッション",
        ["Ui.Stop"] = "停止",
        ["Ui.Restart"] = "再起動",
        ["Ui.Reset"] = "リセット",
        ["Ui.Clear"] = "クリア",
        ["Ui.Inspect"] = "詳細",
        ["Explorer.Title"] = "シンボル エクスプローラー",
        ["Explorer.Subtitle"] = "名前空間・型・メソッド",
        ["Explorer.Filter"] = "シンボルを検索…",
        ["Explorer.FilterTooltip"] = "名前空間、型、メソッド、コメント、アセンブリで検索",
        ["Explorer.Empty"] = "一致するシンボルがありません",
        ["Explorer.EmptyHint"] = "別の名前空間、型、メソッド名を試してください。",
        ["Docs.Summary"] = "概要",
        ["Docs.Parameters"] = "パラメーター",
        ["Docs.Returns"] = "戻り値",
        ["Workspace.Title"] = "ワークスペース",
        ["Workspace.Subtitle"] = "セッション状態と依存関係",
        ["Tab.Variables"] = "変数",
        ["Tab.NuGet"] = "NuGet",
        ["Tab.Libraries"] = "ライブラリ",
        ["Tab.Usings"] = "using",
        ["Tab.Settings"] = "設定",
        ["Column.Kind"] = "種類",
        ["Column.Name"] = "名前",
        ["Column.Type"] = "型",
        ["Column.Value"] = "値",
        ["Column.Version"] = "バージョン",
        ["Column.Source"] = "ソース",
        ["Variables.Empty"] = "変数はまだありません",
        ["Variables.EmptyHint"] = "変数を宣言するとここに表示されます。",
        ["NuGet.SearchTooltip"] = "パッケージID、タイトル、説明、タグ",
        ["NuGet.Search"] = "検索",
        ["NuGet.IncludePrerelease"] = "プレリリースを含める",
        ["NuGet.Verified"] = "  認証済み",
        ["NuGet.Install"] = "追加",
        ["NuGet.DownloadsSuffix"] = " ダウンロード",
        ["Libraries.Empty"] = "追加済みライブラリはありません",
        ["Libraries.EmptyHint"] = "パッケージまたはDLLを追加してください。",
        ["Settings.ExecutionKey"] = "実行キー",
        ["Settings.Theme"] = "テーマ",
        ["Settings.Language"] = "表示言語",
        ["Settings.Security"] = "任意のC#コードは現在のWindowsユーザー権限で実行されます。",
        ["Inspector.Title"] = "結果インスペクター",
        ["Inspector.Snapshot"] = "Workerで取得したスナップショット",
        ["Status.StartingWorker"] = "Workerを起動中",
        ["Status.WorkerDisconnected"] = "Worker未接続",
        ["Status.Ready"] = "準備完了",
        ["Status.Compiling"] = "コンパイル中",
        ["Status.Cancelling"] = "停止中",
        ["Status.Running"] = "実行中",
        ["Status.RestoringPackage"] = "パッケージを復元中",
        ["Status.SearchingPackages"] = "パッケージを検索中",
        ["Status.PackageSearchFailed"] = "パッケージ検索に失敗",
        ["Status.PackageInstallFailed"] = "パッケージ追加に失敗",
        ["Status.Completions"] = "{0} 件の候補",
        ["Status.AddedUsing"] = "using {0} を追加しました",
        ["Status.UsingFailed"] = "usingの追加に失敗",
        ["Session.Count"] = "{0} 件のSubmission",
        ["Session.Memory"] = "{0} 件のSubmission — Worker {1:N0} MiB",
        ["Session.StateLost"] = "0 件のSubmission — Worker状態を消失",
        ["Session.Restarted"] = "0 件のSubmission — Worker再起動済み",
        ["Diagnostics.Count"] = "エラー {0}、警告 {1}",
        ["Cursor.Position"] = "{0} 行、{1} 列",
        ["Explorer.Loading"] = "読み込み中…",
        ["Explorer.Unavailable"] = "Explorerを利用できません",
        ["Explorer.Count"] = "型 {0:N0} · メソッド {1:N0}",
        ["Explorer.Matches"] = "{0:N0} 件一致",
        ["Package.SearchPrompt"] = "nuget.orgからパッケージを検索",
        ["Package.Searching"] = "nuget.orgを検索中…",
        ["Package.NoneFound"] = "パッケージが見つかりません。",
        ["Package.Found"] = "{0:N0} 件中 {1} 件を表示",
        ["Package.Installing"] = "{0} {1} を追加中…",
        ["Package.LatestStable"] = "最新安定版",
        ["Package.Installed"] = "{0} を追加しました。",
        ["Package.InstalledVersion"] = "{0} {1} を追加しました。",
        ["Package.AlreadyInstalled"] = "{0} {1} は追加済みです。",
        ["Assist.CompletionHint"] = "Tab: 補完  ↑↓: 選択  Esc: 閉じる",
        ["Assist.SignatureHint"] = "{0} オーバーロード · 第{1}引数 · ↑↓: 切替",
        ["Message.WorkerConnected"] = "Workerへ接続しました。信頼できないコードやパッケージを実行しないでください。",
        ["Message.ExecutionCancelled"] = "実行を停止しました。",
        ["Message.SessionReset"] = "セッションをリセットしました。",
        ["Message.WorkerRestarted"] = "Workerを再起動しました。変数とメソッドは失われ、参照とusingは復元されました。",
        ["Message.ForcedRestart"] = "停止できないためWorkerを強制終了しました。Transcriptと入力履歴は保持されましたが、セッション変数は失われました。",
        ["Message.PackageAdded"] = "パッケージを追加しました: {0} {1}",
        ["Message.UsingAdded"] = "usingを追加しました: {0}",
        ["Message.UsingActive"] = "usingは追加済みです: {0}",
        ["Message.ReferenceAdded"] = "参照を追加しました: {0}",
        ["Message.NoReferences"] = "動的参照はありません。",
        ["Message.NoPackages"] = "パッケージはありません。",
        ["Message.UnknownCommand"] = "不明なコマンド: {0}",
        ["Completion.Command"] = "PlayGroundSharp コマンド",
        ["Completion.Namespace"] = "追加済みアセンブリの名前空間です。Tabでusingコマンドを挿入します。"
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["Ui.AppSubtitle"] = "C# interactive console", ["Ui.Types"] = "Types", ["Ui.Session"] = "Session",
        ["Ui.Stop"] = "Stop", ["Ui.Restart"] = "Restart", ["Ui.Reset"] = "Reset", ["Ui.Clear"] = "Clear", ["Ui.Inspect"] = "Inspect",
        ["Explorer.Title"] = "Symbol Explorer", ["Explorer.Subtitle"] = "Namespaces, types and methods",
        ["Explorer.Filter"] = "Filter symbols…", ["Explorer.FilterTooltip"] = "Filter by namespace, type, method, documentation or assembly",
        ["Explorer.Empty"] = "No matching symbols", ["Explorer.EmptyHint"] = "Try another namespace, type or method name.",
        ["Docs.Summary"] = "Summary", ["Docs.Parameters"] = "Parameters", ["Docs.Returns"] = "Returns",
        ["Workspace.Title"] = "Workspace", ["Workspace.Subtitle"] = "Session state and dependencies",
        ["Tab.Variables"] = "Variables", ["Tab.NuGet"] = "NuGet", ["Tab.Libraries"] = "Libraries", ["Tab.Usings"] = "Usings", ["Tab.Settings"] = "Settings",
        ["Column.Kind"] = "Kind", ["Column.Name"] = "Name", ["Column.Type"] = "Type", ["Column.Value"] = "Value", ["Column.Version"] = "Version", ["Column.Source"] = "Source",
        ["Variables.Empty"] = "No variables yet", ["Variables.EmptyHint"] = "Run a declaration to populate this view.",
        ["NuGet.SearchTooltip"] = "Package ID, title, description or tag", ["NuGet.Search"] = "Search", ["NuGet.IncludePrerelease"] = "Include prerelease",
        ["NuGet.Verified"] = "  Verified", ["NuGet.Install"] = "Install", ["NuGet.DownloadsSuffix"] = " downloads",
        ["Libraries.Empty"] = "No imported libraries", ["Libraries.EmptyHint"] = "Install a package or add a DLL.",
        ["Settings.ExecutionKey"] = "Execution key", ["Settings.Theme"] = "Theme", ["Settings.Language"] = "Language",
        ["Settings.Security"] = "Arbitrary C# runs with your Windows user permissions.",
        ["Inspector.Title"] = "Result Inspector", ["Inspector.Snapshot"] = "Snapshot captured in Worker",
        ["Status.StartingWorker"] = "Starting Worker", ["Status.WorkerDisconnected"] = "Worker disconnected", ["Status.Ready"] = "Ready",
        ["Status.Compiling"] = "Compiling", ["Status.Cancelling"] = "Cancelling", ["Status.Running"] = "Running",
        ["Status.RestoringPackage"] = "Restoring package", ["Status.SearchingPackages"] = "Searching packages",
        ["Status.PackageSearchFailed"] = "Package search failed", ["Status.PackageInstallFailed"] = "Package install failed",
        ["Status.Completions"] = "{0} completions", ["Status.AddedUsing"] = "Added using {0}", ["Status.UsingFailed"] = "Using import failed",
        ["Session.Count"] = "{0} submissions", ["Session.Memory"] = "{0} submissions — Worker {1:N0} MiB",
        ["Session.StateLost"] = "0 submissions — Worker state lost", ["Session.Restarted"] = "0 submissions — Worker restarted",
        ["Diagnostics.Count"] = "{0} errors, {1} warnings", ["Cursor.Position"] = "Ln {0}, Col {1}",
        ["Explorer.Loading"] = "Loading…", ["Explorer.Unavailable"] = "Explorer unavailable",
        ["Explorer.Count"] = "{0:N0} types · {1:N0} methods", ["Explorer.Matches"] = "{0:N0} matches",
        ["Package.SearchPrompt"] = "Search packages on nuget.org", ["Package.Searching"] = "Searching nuget.org…",
        ["Package.NoneFound"] = "No packages found.", ["Package.Found"] = "{0:N0} packages found — showing {1}",
        ["Package.Installing"] = "Installing {0} {1}…", ["Package.LatestStable"] = "latest stable",
        ["Package.Installed"] = "Installed {0}.", ["Package.InstalledVersion"] = "Installed {0} {1}.",
        ["Package.AlreadyInstalled"] = "{0} {1} is already installed.",
        ["Assist.CompletionHint"] = "Tab: complete  ↑↓: select  Esc: close",
        ["Assist.SignatureHint"] = "{0} overload(s) · parameter {1} · ↑↓: switch",
        ["Message.WorkerConnected"] = "Worker connected. Do not execute untrusted code or packages.",
        ["Message.ExecutionCancelled"] = "Execution cancelled.", ["Message.SessionReset"] = "Session reset.",
        ["Message.WorkerRestarted"] = "Worker restarted. Variables and methods were lost; references and usings were restored.",
        ["Message.ForcedRestart"] = "Worker was terminated because cancellation did not complete. Session variables were lost; transcript and input history were preserved.",
        ["Message.PackageAdded"] = "Package added: {0} {1}", ["Message.UsingAdded"] = "Using added: {0}",
        ["Message.UsingActive"] = "Using already active: {0}", ["Message.ReferenceAdded"] = "Reference added: {0}",
        ["Message.NoReferences"] = "No dynamic references.", ["Message.NoPackages"] = "No packages.",
        ["Message.UnknownCommand"] = "Unknown command: {0}", ["Completion.Command"] = "PlayGroundSharp command",
        ["Completion.Namespace"] = "Namespace from an added assembly; Tab inserts the using command."
    };

    public static IReadOnlyDictionary<string, string> Resources(AppLanguageMode mode) =>
        mode == AppLanguageMode.Japanese ? Japanese : English;

    public static string Text(AppLanguageMode mode, string key, params object?[] arguments)
    {
        var value = Resources(mode).GetValueOrDefault(key) ?? key;
        return arguments.Length == 0 ? value : string.Format(value, arguments);
    }
}
