namespace PlayGroundSharp.App;

internal static class AppLocalization
{
    private static readonly IReadOnlyDictionary<string, string> Japanese = new Dictionary<string, string>
    {
        ["Ui.AppSubtitle"] = "C# 対話コンソール",
        ["Ui.Types"] = "型",
        ["Ui.Session"] = "セッション",
        ["Ui.Stop"] = "停止",
        ["Ui.Restart"] = "再起動",
        ["Ui.Reset"] = "リセット",
        ["Ui.Clear"] = "クリア",
        ["Ui.Inspect"] = "詳細",
        ["Ui.Copy"] = "コピー",
        ["Ui.CopyJson"] = "JSONとしてコピー",
        ["Ui.Save"] = "保存",
        ["Ui.ScrollToLatest"] = "最新の出力へ移動",
        ["Tooltip.Types"] = "シンボル エクスプローラーを開閉します",
        ["Tooltip.Session"] = "変数・NuGet・ライブラリ・using・設定を開閉します",
        ["Tooltip.Stop"] = "実行中のコードを停止します。応答しない場合はWorkerを再起動します",
        ["Tooltip.Restart"] = "Workerを再起動します。セッション内の変数・型・メソッドは失われます",
        ["Tooltip.Reset"] = "Submission状態をリセットします。追加した参照とusingは維持されます",
        ["Tooltip.Clear"] = "画面上のTranscriptだけをクリアします。セッション状態は維持されます",
        ["Tooltip.ResizeExplorer"] = "ドラッグしてシンボル エクスプローラーの幅を変更します",
        ["Tooltip.ResizeWorkspace"] = "ドラッグしてワークスペース パネルの幅を変更します",
        ["Tooltip.ResizeCompletion"] = "ドラッグして候補一覧とドキュメントの幅を変更します",
        ["Drop.InsertPath"] = "パスを挿入",
        ["Drop.InsertPathArray"] = "パス配列を挿入",
        ["Drop.InspectFiles"] = "ファイル情報一覧を作るコードを挿入",
        ["Drop.ReadJsonFiles"] = "複数JSONを読み込むコードを挿入",
        ["Drop.Hint"] = "ファイル／フォルダーをここにドロップ",
        ["Drop.FileInfo"] = "ファイル情報を読み込むコードを挿入",
        ["Drop.TextPreview"] = "テキストプレビューのコードを挿入",
        ["Drop.ReadLines"] = "行ストリームのコードを挿入",
        ["Drop.ReadJson"] = "JSONとして読み込むコードを挿入",
        ["Drop.ReadJsonArray"] = "JSON配列として読み込むコードを挿入",
        ["Drop.ReadJsonLines"] = "JSON Linesとして読み込むコードを挿入",
        ["Drop.ReadBytes"] = "バイト列として読み込むコードを挿入",
        ["Drop.EnumerateFiles"] = "直下のファイル列挙を挿入",
        ["Drop.EnumerateFilesRecursive"] = "配下のファイル列挙を挿入",
        ["Menu.File"] = "ファイル",
        ["Menu.Edit"] = "編集",
        ["Menu.Data"] = "データ",
        ["Menu.View"] = "表示",
        ["Menu.Help"] = "ヘルプ",
        ["Menu.SaveWorkspace"] = "ワークスペースを保存…",
        ["Menu.OpenWorkspace"] = "ワークスペースを開く…",
        ["Menu.Exit"] = "終了",
        ["Menu.FocusInput"] = "入力欄へ移動",
        ["Menu.SearchSymbols"] = "シンボルを検索",
        ["Menu.ClearTranscript"] = "Transcriptをクリア",
        ["Menu.CopyTranscript"] = "Transcript全体をコピー",
        ["Menu.SaveTranscript"] = "Transcript全体を保存…",
        ["Menu.InspectFile"] = "ファイル情報を挿入…",
        ["Menu.PreviewText"] = "テキストプレビューを挿入…",
        ["Menu.ReadLines"] = "行ストリームを挿入…",
        ["Menu.ReadJson"] = "JSONの読み込みを挿入…",
        ["Menu.ReadJsonArray"] = "JSON配列の読み込みを挿入…",
        ["Menu.ReadJsonLines"] = "JSON Linesの読み込みを挿入…",
        ["Menu.SymbolExplorer"] = "シンボル エクスプローラー",
        ["Menu.Workspace"] = "ワークスペース パネル",
        ["Menu.OpenHelp"] = "PlayGroundSharp ヘルプ",
        ["Menu.About"] = "PlayGroundSharpについて",
        ["Explorer.Title"] = "シンボル エクスプローラー",
        ["Explorer.Subtitle"] = "名前空間・型・メソッド",
        ["Explorer.Filter"] = "シンボルを検索…",
        ["Explorer.FilterTooltip"] = "名前空間、型、メソッド、コメント、アセンブリで検索",
        ["Explorer.Empty"] = "一致するシンボルがありません",
        ["Explorer.EmptyHint"] = "別の名前空間、型、メソッド名を試してください。",
        ["Docs.Summary"] = "概要",
        ["Docs.NoSummary"] = "概要はありません。",
        ["Docs.Inheritance"] = "継承・実装",
        ["Docs.Parameters"] = "パラメーター",
        ["Docs.Returns"] = "戻り値",
        ["Docs.OpenJapanese"] = "Microsoft Learn 日本語版を開く",
        ["Docs.HoverHint"] = "クリックすると詳細を固定表示します",
        ["Workspace.Title"] = "ワークスペース",
        ["Workspace.Subtitle"] = "セッション状態と依存関係",
        ["Tab.Variables"] = "変数",
        ["Tab.NuGet"] = "NuGet",
        ["Tab.Libraries"] = "ライブラリ",
        ["Tab.Usings"] = "using",
        ["Tab.Settings"] = "設定",
        ["Usings.Add"] = "追加",
        ["Usings.Remove"] = "削除",
        ["Usings.InputTooltip"] = "名前空間またはusingディレクティブ（例: System.Net.Http）。Enterで追加、Escでクリアまたはエディターへ戻ります。",
        ["Usings.ListTooltip"] = "×またはDeleteキーで削除します。セッション状態がある場合は確認します。",
        ["Column.Kind"] = "種類",
        ["Column.Name"] = "名前",
        ["Column.Type"] = "型",
        ["Column.Value"] = "値",
        ["Column.Version"] = "バージョン",
        ["Column.Source"] = "ソース",
        ["Variables.Empty"] = "変数はまだありません",
        ["Variables.EmptyHint"] = "変数を宣言するとここに表示されます。",
        ["Variables.Filter"] = "変数を検索…",
        ["Variables.NoMatches"] = "一致する変数はありません",
        ["Variables.InteractionHint"] = "ダブルクリックまたはEnterで変数名を入力。Ctrl+Cで値をコピー、右クリックでコピー・詳細表示できます。",
        ["NuGet.SearchTooltip"] = "パッケージID、タイトル、説明、タグ。Enterで検索、↓で結果へ移動、Escでクリアまたは入力欄へ戻ります。",
        ["NuGet.Search"] = "検索",
        ["NuGet.IncludePrerelease"] = "プレリリースを含める",
        ["NuGet.Verified"] = "  認証済み",
        ["NuGet.Install"] = "追加",
        ["NuGet.DownloadsSuffix"] = " ダウンロード",
        ["Libraries.Empty"] = "追加済みライブラリはありません",
        ["Libraries.EmptyHint"] = "パッケージまたはDLLを追加してください。",
        ["Settings.ExecutionKey"] = "実行キー",
        ["Settings.Theme"] = "テーマ",
        ["Settings.Language"] = "表示言語",
        ["Settings.Security"] = "任意のC#コードは現在のWindowsユーザー権限で実行されます。",
        ["Inspector.Title"] = "結果インスペクター",
        ["Inspector.Snapshot"] = "Workerで取得したスナップショット",
        ["Inspector.Expand"] = "展開",
        ["Inspector.Collapse"] = "折りたたむ",
        ["Inspector.CopySelected"] = "選択をコピー",
        ["Inspector.CopyAll"] = "全体をコピー",
        ["Inspector.CopyPath"] = "パスをコピー",
        ["Inspector.SaveAll"] = "全体を保存",
        ["Inspector.Search"] = "検索",
        ["Inspector.SearchTooltip"] = "Ctrl+Fで検索。Enterまたは↓で結果へ移動し、Escで検索をクリアします。",
        ["Inspector.CopySelectedTooltip"] = "選択した値をコピー (Ctrl+C)",
        ["Inspector.CopyAllTooltip"] = "結果全体をコピー (Ctrl+Shift+C)",
        ["Inspector.SaveAllTooltip"] = "結果全体を保存 (Ctrl+S)",
        ["Inspector.Searching"] = "検索中…",
        ["Inspector.NoMatches"] = "一致なし",
        ["Inspector.MatchCount"] = "{0:N0} 件",
        ["Inspector.MatchCountLimited"] = "{0:N0} 件中、先頭 {1:N0} 件を表示",
        ["Inspector.ItemRange"] = "[{0:N0} … {1:N0}]",
        ["Inspector.PropertyRange"] = "プロパティ {0:N0}～{1:N0}",
        ["Inspector.MatchRange"] = "一致 {0:N0}～{1:N0}",
        ["Inspector.Path"] = "パス",
        ["Inspector.Type"] = "型",
        ["Inspector.Count"] = "件数",
        ["Inspector.Captured"] = "{0:N0} 件取得",
        ["Inspector.UnknownType"] = "不明",
        ["Inspector.ItemSummary"] = "[{0:N0} 項目]",
        ["Inspector.PropertySummary"] = "{{{0:N0} プロパティ}}",
        ["Output.PreviewLimited"] = "※ 表示はプレビューです。［詳細］から構造を確認し、全体をコピーできます。",
        ["Output.CaptureLimited"] = "※ 安全上限に達したため、Workerで取得できた範囲を表示しています。",
        ["Output.ConsolePreviewLimited"] = "… 画面表示はプレビューです（このチャンクは {0:N0} 文字）。［編集］からTranscript全体をコピーまたは保存できます。",
        ["Status.StartingWorker"] = "Workerを起動中",
        ["Status.WorkerDisconnected"] = "Worker未接続",
        ["Status.Ready"] = "準備完了",
        ["Status.PreparingExecution"] = "入力とusingを解析中",
        ["Status.Compiling"] = "コンパイル中",
        ["Status.Cancelling"] = "停止中",
        ["Status.Running"] = "実行中",
        ["Status.RestoringPackage"] = "パッケージを復元中",
        ["Status.SearchingPackages"] = "パッケージを検索中",
        ["Status.PackageSearchFailed"] = "パッケージ検索に失敗",
        ["Status.PackageInstallFailed"] = "パッケージ追加に失敗",
        ["Status.Completions"] = "{0} 件の候補",
        ["Status.AddedUsing"] = "using {0} を追加しました",
        ["Status.UsingFailed"] = "usingの追加に失敗",
        ["Status.SessionBusy"] = "別のセッション操作が完了するまでお待ちください",
        ["Status.DropChooseAction"] = "ドロップしたパスの操作を選択してください",
        ["Status.DroppedPath"] = "ドロップしたパスからコードを挿入しました",
        ["Status.DroppedPaths"] = "ドロップした{0}件のパス配列を挿入しました",
        ["Status.SnippetInserted"] = "データ読み込みコードを入力欄へ挿入しました",
        ["Status.Copying"] = "コピーする内容を準備中",
        ["Status.CopyFailed"] = "コピーに失敗しました",
        ["Status.Copied"] = "クリップボードにコピーしました",
        ["Status.CopiedJson"] = "JSONをクリップボードにコピーしました",
        ["Status.SavingResult"] = "結果を保存中",
        ["Status.SaveFailed"] = "結果の保存に失敗しました",
        ["Status.Saved"] = "保存しました: {0}",
        ["Message.DropPathsLimited"] = "一度に挿入できるパスは{0:N0}件までです。残り{1:N0}件は省略しました。",
        ["Message.PackageOperationCancelled"] = "NuGetの検索またはパッケージ追加をキャンセルしました。",
        ["Status.RemovedUsing"] = "using {0} を削除しました",
        ["Status.SavingWorkspace"] = "ワークスペースを保存中",
        ["Status.LoadingWorkspace"] = "ワークスペースを読み込み中",
        ["Status.ReplayingWorkspace"] = "ワークスペースを再生中 ({0}/{1})",
        ["Status.WorkspaceLoaded"] = "ワークスペースを読み込みました",
        ["Status.WorkspaceLoadFailed"] = "ワークスペースの読み込みに失敗",
        ["Session.Count"] = "{0} 件のSubmission",
        ["Session.Memory"] = "{0} 件のSubmission — Worker {1:N0} MiB",
        ["Session.StateLost"] = "0 件のSubmission — Worker状態を消失",
        ["Session.Restarted"] = "0 件のSubmission — Worker再起動済み",
        ["Diagnostics.Count"] = "エラー {0}、警告 {1}",
        ["Diagnostics.Deferred"] = "実行完了後に診断を更新",
        ["Diagnostics.DeferredDetail"] = "現在の実行で追加される変数や型を反映してから診断します。",
        ["Diagnostics.Checking"] = "診断を更新中…",
        ["Diagnostics.CheckingDetail"] = "入力が止まってからエラーと警告を確認します。",
        ["Diagnostics.NavigateHint"] = "クリックまたはF8で次へ、Shift+F8で前へ移動します。",
        ["Diagnostics.More"] = "ほか {0:N0} 件",
        ["Diagnostics.Unavailable"] = "診断を更新できませんでした",
        ["Status.DiagnosticLocation"] = "診断 {0}/{1}: {2} ({3},{4})",
        ["Cursor.Position"] = "{0} 行、{1} 列",
        ["Explorer.Loading"] = "読み込み中…",
        ["Explorer.Filtering"] = "絞り込み中…",
        ["Explorer.Unavailable"] = "Explorerを利用できません",
        ["Explorer.Count"] = "型 {0:N0} · メソッド {1:N0} · enum値 {2:N0}",
        ["Explorer.Matches"] = "{0:N0} 件一致",
        ["Explorer.MatchesLimited"] = "{0:N0} 件一致 · 先頭 {1:N0} 件を表示",
        ["Package.SearchPrompt"] = "nuget.orgからパッケージを検索",
        ["Package.Searching"] = "nuget.orgを検索中…",
        ["Package.Cancelled"] = "NuGet操作をキャンセルしました。",
        ["Package.NoneFound"] = "パッケージが見つかりません。",
        ["Package.Found"] = "{0:N0} 件中 {1} 件を表示",
        ["Package.QueryChanged"] = "「{0}」の検索が完了しました。現在の検索語でEnterを押してください。",
        ["Package.CriteriaChanged"] = "検索条件が変わりました。Enterで再検索してください。",
        ["Package.Installing"] = "{0} {1} を追加中…",
        ["Package.InstallingLatest"] = "{0} の最新安定版を追加中…",
        ["Package.LatestStable"] = "最新安定版",
        ["Package.Installed"] = "{0} を追加しました。",
        ["Package.InstalledVersion"] = "{0} {1} を追加しました。",
        ["Package.AlreadyInstalled"] = "{0} {1} は追加済みです。",
        ["Assist.CompletionHint"] = "Tab: 補完  ↑↓: 選択  PageUp/PageDown: ページ移動  Esc: 閉じる",
        ["Assist.SignatureHint"] = "{0} オーバーロード · 引数 {1}/{2}: {3} · ↑↓: 切替",
        ["Assist.SignatureHintNoParameter"] = "{0} オーバーロード · ↑↓: 切替",
        ["Assist.ActiveParameter"] = "入力中の引数: {0} {1}",
        ["Assist.NoParameterDocumentation"] = "この引数の説明はありません。",
        ["Assist.Documentation"] = "ドキュメント",
        ["Assist.LoadingDocumentation"] = "ドキュメントを読み込み中…",
        ["Assist.AutoImport"] = "確定すると using {0} を自動追加します。",
        ["Assist.NoDocumentation"] = "この候補のドキュメントはありません。",
        ["Assist.DocumentationLanguageHint"] = "参照ライブラリに付属する原文を表示します。日本語版はシンボル エクスプローラーからMicrosoft Learnを開けます。",
        ["QuickInfo.Hint"] = "Escで閉じる · Ctrl+K, Ctrl+Iで再表示",
        ["Status.QuickInfoChord"] = "続けてCtrl+Iを押すとクイック情報を表示します",
        ["Status.QuickInfoShown"] = "キャレット位置のクイック情報を表示しました",
        ["Status.QuickInfoUnavailable"] = "キャレット位置に表示できる情報はありません",
        ["Message.WorkerConnected"] = "Workerへ接続しました。信頼できないコードやパッケージを実行しないでください。",
        ["Message.WorkerDisconnected"] = "Workerが予期せず切断されました（{0}）。再起動すると操作を続けられます。",
        ["Message.WorkerEventApplyFailed"] = "Workerから受信した{0}の画面反映に失敗しました: {1}",
        ["Message.WorkerExitCode"] = "終了コード {0}",
        ["Message.WorkerExitDetail"] = "終了コード {0}: {1}",
        ["Message.WorkerPipeClosed"] = "通信チャネルが閉じられました",
        ["Message.WorkerUnavailable"] = "Workerに接続されていません。先にWorkerを再起動してください。",
        ["Message.ExecutionCancelled"] = "実行を停止しました。",
        ["Message.SessionReset"] = "セッションをリセットしました。",
        ["Message.WorkerRestarted"] = "Workerを再起動しました。変数とメソッドは失われ、参照とusingは復元されました。",
        ["Message.ForcedRestart"] = "停止できないためWorkerを強制終了しました。Transcriptと入力履歴は保持されましたが、セッション変数は失われました。",
        ["Message.SessionBusy"] = "実行中または別のセッション操作中です。完了を待つか、実行を停止してください。",
        ["Message.PackageAdded"] = "パッケージを追加しました: {0} {1}",
        ["Message.UsingAdded"] = "usingを追加しました: {0}",
        ["Message.UsingAutoAdded"] = "補完候補からusingを自動追加しました: {0}",
        ["Message.UsingExecutionAutoAdded"] = "実行前にusingを自動追加しました: {0}",
        ["Message.UsingActive"] = "usingは追加済みです: {0}",
        ["Message.UsingRemoved"] = "usingを削除しました: {0}",
        ["Message.UsingRemovedWithRestart"] = "using {0} を削除するためWorkerを再構築しました。セッション変数・型・メソッドは失われました。",
        ["Message.UsingMissing"] = "usingは見つかりません: {0}",
        ["Message.ReferenceAdded"] = "参照を追加しました: {0}",
        ["Message.NoReferences"] = "動的参照はありません。",
        ["Message.NoPackages"] = "パッケージはありません。",
        ["Message.UnknownCommand"] = "不明なコマンド: {0}",
        ["Message.WorkspaceSaved"] = "ワークスペースを保存しました: {0}",
        ["Message.WorkspaceLoaded"] = "ワークスペースを読み込み、{0}件のSubmissionを再生しました。",
        ["Message.ReferenceMissing"] = "参照ファイルが見つからないためスキップしました: {0}",
        ["Message.ReplayFailed"] = "Submission {0} の再生に失敗しました。",
        ["Dialog.WorkspaceLoadTitle"] = "ワークスペースを開く",
        ["Dialog.WorkspaceLoadWarning"] = "現在のWorker状態を破棄し、保存済みSubmissionを順番に再実行します。ファイル操作などの副作用も再実行されます。続行しますか？",
        ["Dialog.UsingRemoveTitle"] = "usingの削除",
        ["Dialog.UsingRemoveWarning"] = "using {0} を削除するにはWorkerの再構築が必要です。現在のセッション変数・型・メソッドは失われますが、Transcript、履歴、参照は保持されます。続行しますか？",
        ["Dialog.RestartTitle"] = "Workerの再起動",
        ["Dialog.RestartWarning"] = "Workerを再起動すると、現在の変数・型・メソッドは失われます。Transcript、履歴、参照は保持されます。続行しますか？",
        ["Dialog.ResetTitle"] = "Submission状態のリセット",
        ["Dialog.ResetWarning"] = "現在の変数・型・メソッドをクリアします。追加済みの参照とusingは維持されます。続行しますか？",
        ["Dialog.ErrorTitle"] = "PlayGroundSharp エラー",
        ["Dialog.WorkspaceFilter"] = "PlayGroundSharp ワークスペース (*.pgsworkspace)|*.pgsworkspace|JSON (*.json)|*.json",
        ["Dialog.DataFileFilter"] = "すべてのファイル (*.*)|*.*|JSON (*.json;*.jsonl)|*.json;*.jsonl|テキスト (*.txt;*.log;*.csv)|*.txt;*.log;*.csv",
        ["Dialog.ResultSaveTitle"] = "結果を保存",
        ["Dialog.TranscriptSaveTitle"] = "Transcriptを保存",
        ["Dialog.TextFileFilter"] = "テキスト (*.txt)|*.txt|すべてのファイル (*.*)|*.*",
        ["Dialog.ResultFileFilter"] = "テキスト (*.txt)|*.txt|JSON (*.json)|*.json|すべてのファイル (*.*)|*.*",
        ["Help.Title"] = "PlayGroundSharp ヘルプ",
        ["Help.SecurityTitle"] = "セキュリティ上の注意",
        ["Help.SecurityMessage"] = "入力したC#コードと追加したパッケージは、現在のWindowsユーザー権限で実行されます。信頼できないコードやパッケージを実行しないでください。",
        ["About.Message"] = "状態保持型C#対話コンソール\n.NET 10 / WPF / Roslyn\n\n任意のコードは現在のWindowsユーザー権限で実行されます。",
        ["Completion.Command"] = "PlayGroundSharp コマンド",
        ["Completion.Namespace"] = "追加済みアセンブリの名前空間です。Tabでusingコマンドを挿入します。"
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["Ui.AppSubtitle"] = "C# interactive console", ["Ui.Types"] = "Types", ["Ui.Session"] = "Session",
        ["Ui.Stop"] = "Stop", ["Ui.Restart"] = "Restart", ["Ui.Reset"] = "Reset", ["Ui.Clear"] = "Clear", ["Ui.Inspect"] = "Inspect", ["Ui.Copy"] = "Copy", ["Ui.CopyJson"] = "Copy as JSON", ["Ui.Save"] = "Save", ["Ui.ScrollToLatest"] = "Scroll to latest output",
        ["Tooltip.Types"] = "Toggle the Symbol Explorer",
        ["Tooltip.Session"] = "Toggle variables, NuGet, libraries, usings, and settings",
        ["Tooltip.Stop"] = "Stop running code; restart the Worker if it does not respond",
        ["Tooltip.Restart"] = "Restart the Worker; session variables, types, and methods are lost",
        ["Tooltip.Reset"] = "Reset submission state while keeping added references and usings",
        ["Tooltip.Clear"] = "Clear only the visible transcript; session state is preserved",
        ["Tooltip.ResizeExplorer"] = "Drag to resize the Symbol Explorer",
        ["Tooltip.ResizeWorkspace"] = "Drag to resize the Workspace panel",
        ["Tooltip.ResizeCompletion"] = "Drag to resize completion items and documentation",
        ["Drop.InsertPath"] = "Insert path",
        ["Drop.InsertPathArray"] = "Insert path array",
        ["Drop.InspectFiles"] = "Insert code to inspect the files",
        ["Drop.ReadJsonFiles"] = "Insert code to read multiple JSON files",
        ["Drop.Hint"] = "Drop files or folders here",
        ["Drop.FileInfo"] = "Insert file information code",
        ["Drop.TextPreview"] = "Insert text preview code",
        ["Drop.ReadLines"] = "Insert line stream code",
        ["Drop.ReadJson"] = "Insert JSON reader code",
        ["Drop.ReadJsonArray"] = "Insert JSON array reader code",
        ["Drop.ReadJsonLines"] = "Insert JSON Lines reader code",
        ["Drop.ReadBytes"] = "Insert byte reader code",
        ["Drop.EnumerateFiles"] = "Insert direct file enumeration",
        ["Drop.EnumerateFilesRecursive"] = "Insert recursive file enumeration",
        ["Menu.File"] = "File", ["Menu.Edit"] = "Edit", ["Menu.Data"] = "Data", ["Menu.View"] = "View", ["Menu.Help"] = "Help",
        ["Menu.SaveWorkspace"] = "Save Workspace…", ["Menu.OpenWorkspace"] = "Open Workspace…", ["Menu.Exit"] = "Exit",
        ["Menu.FocusInput"] = "Focus Input", ["Menu.ClearTranscript"] = "Clear Transcript",
        ["Menu.SearchSymbols"] = "Search Symbols",
        ["Menu.CopyTranscript"] = "Copy Entire Transcript", ["Menu.SaveTranscript"] = "Save Entire Transcript…",
        ["Menu.InspectFile"] = "Insert File Info…", ["Menu.PreviewText"] = "Insert Text Preview…",
        ["Menu.ReadLines"] = "Insert Line Stream…", ["Menu.ReadJson"] = "Insert JSON Reader…", ["Menu.ReadJsonArray"] = "Insert JSON Array Reader…",
        ["Menu.ReadJsonLines"] = "Insert JSON Lines Reader…", ["Menu.SymbolExplorer"] = "Symbol Explorer",
        ["Menu.Workspace"] = "Workspace Panel", ["Menu.OpenHelp"] = "PlayGroundSharp Help", ["Menu.About"] = "About PlayGroundSharp",
        ["Explorer.Title"] = "Symbol Explorer", ["Explorer.Subtitle"] = "Namespaces, types and methods",
        ["Explorer.Filter"] = "Filter symbols…", ["Explorer.FilterTooltip"] = "Filter by namespace, type, method, documentation or assembly",
        ["Explorer.Empty"] = "No matching symbols", ["Explorer.EmptyHint"] = "Try another namespace, type or method name.",
        ["Docs.Summary"] = "Summary", ["Docs.NoSummary"] = "No summary is available.", ["Docs.Inheritance"] = "Inherits / implements", ["Docs.Parameters"] = "Parameters", ["Docs.Returns"] = "Returns",
        ["Docs.OpenJapanese"] = "Open Microsoft Learn", ["Docs.HoverHint"] = "Click to pin details",
        ["Workspace.Title"] = "Workspace", ["Workspace.Subtitle"] = "Session state and dependencies",
        ["Tab.Variables"] = "Variables", ["Tab.NuGet"] = "NuGet", ["Tab.Libraries"] = "Libraries", ["Tab.Usings"] = "Usings", ["Tab.Settings"] = "Settings",
        ["Usings.Add"] = "Add", ["Usings.Remove"] = "Remove", ["Usings.InputTooltip"] = "Namespace or using directive (for example, System.Net.Http). Enter adds; Esc clears or returns to the editor.",
        ["Usings.ListTooltip"] = "Remove with × or Delete. Existing session state requires confirmation.",
        ["Column.Kind"] = "Kind", ["Column.Name"] = "Name", ["Column.Type"] = "Type", ["Column.Value"] = "Value", ["Column.Version"] = "Version", ["Column.Source"] = "Source",
        ["Variables.Empty"] = "No variables yet", ["Variables.EmptyHint"] = "Run a declaration to populate this view.",
        ["Variables.Filter"] = "Search variables…", ["Variables.NoMatches"] = "No matching variables",
        ["Variables.InteractionHint"] = "Double-click or press Enter to insert a variable name. Ctrl+C copies its value; right-click to copy or inspect.",
        ["NuGet.SearchTooltip"] = "Package ID, title, description or tag. Enter searches, Down moves to results, and Esc clears or returns to input.", ["NuGet.Search"] = "Search", ["NuGet.IncludePrerelease"] = "Include prerelease",
        ["NuGet.Verified"] = "  Verified", ["NuGet.Install"] = "Install", ["NuGet.DownloadsSuffix"] = " downloads",
        ["Libraries.Empty"] = "No imported libraries", ["Libraries.EmptyHint"] = "Install a package or add a DLL.",
        ["Settings.ExecutionKey"] = "Execution key", ["Settings.Theme"] = "Theme", ["Settings.Language"] = "Language",
        ["Settings.Security"] = "Arbitrary C# runs with your Windows user permissions.",
        ["Inspector.Title"] = "Result Inspector", ["Inspector.Snapshot"] = "Snapshot captured in Worker",
        ["Inspector.Expand"] = "Expand", ["Inspector.Collapse"] = "Collapse",
        ["Inspector.CopySelected"] = "Copy selected", ["Inspector.CopyAll"] = "Copy all",
        ["Inspector.CopyPath"] = "Copy path", ["Inspector.SaveAll"] = "Save all", ["Inspector.Search"] = "Search",
        ["Inspector.SearchTooltip"] = "Ctrl+F to search. Enter or Down moves to results; Esc clears the search.",
        ["Inspector.CopySelectedTooltip"] = "Copy selected value (Ctrl+C)",
        ["Inspector.CopyAllTooltip"] = "Copy the entire result (Ctrl+Shift+C)",
        ["Inspector.SaveAllTooltip"] = "Save the entire result (Ctrl+S)",
        ["Inspector.Searching"] = "Searching…",
        ["Inspector.NoMatches"] = "No matches", ["Inspector.MatchCount"] = "{0:N0} matches",
        ["Inspector.MatchCountLimited"] = "{0:N0} matches · showing first {1:N0}",
        ["Inspector.ItemRange"] = "[{0:N0} … {1:N0}]", ["Inspector.PropertyRange"] = "properties {0:N0}–{1:N0}",
        ["Inspector.MatchRange"] = "matches {0:N0}–{1:N0}",
        ["Inspector.Path"] = "Path", ["Inspector.Type"] = "Type", ["Inspector.Count"] = "Count",
        ["Inspector.Captured"] = "{0:N0} captured", ["Inspector.UnknownType"] = "unknown",
        ["Inspector.ItemSummary"] = "[{0:N0} items]", ["Inspector.PropertySummary"] = "{{{0:N0} properties}}",
        ["Output.PreviewLimited"] = "Preview only. Open Inspect to browse the structure and copy the complete captured result.",
        ["Output.CaptureLimited"] = "The Worker safety limit was reached; the captured portion is shown.",
        ["Output.ConsolePreviewLimited"] = "… Display preview only ({0:N0} characters in this chunk). Use Edit to copy or save the entire transcript.",
        ["Status.StartingWorker"] = "Starting Worker", ["Status.WorkerDisconnected"] = "Worker disconnected", ["Status.Ready"] = "Ready",
        ["Status.PreparingExecution"] = "Analyzing input and usings",
        ["Status.Compiling"] = "Compiling", ["Status.Cancelling"] = "Cancelling", ["Status.Running"] = "Running",
        ["Status.RestoringPackage"] = "Restoring package", ["Status.SearchingPackages"] = "Searching packages",
        ["Status.PackageSearchFailed"] = "Package search failed", ["Status.PackageInstallFailed"] = "Package install failed",
        ["Status.Completions"] = "{0} completions", ["Status.AddedUsing"] = "Added using {0}", ["Status.UsingFailed"] = "Using import failed",
        ["Status.SessionBusy"] = "Wait for the current session operation to finish",
        ["Status.DropChooseAction"] = "Choose an action for the dropped path",
        ["Status.DroppedPath"] = "Inserted code for the dropped path",
        ["Status.DroppedPaths"] = "Inserted an array containing {0} dropped paths",
        ["Status.SnippetInserted"] = "Inserted data-loading code into the input",
        ["Status.Copying"] = "Preparing content to copy", ["Status.CopyFailed"] = "Copy failed",
        ["Status.Copied"] = "Copied to the clipboard", ["Status.Saved"] = "Saved: {0}",
        ["Status.CopiedJson"] = "Copied JSON to the clipboard",
        ["Status.SavingResult"] = "Saving result", ["Status.SaveFailed"] = "Result save failed",
        ["Message.DropPathsLimited"] = "At most {0:N0} paths can be inserted at once; {1:N0} additional paths were omitted.",
        ["Message.PackageOperationCancelled"] = "Cancelled the NuGet search or package installation.",
        ["Status.RemovedUsing"] = "Removed using {0}",
        ["Status.SavingWorkspace"] = "Saving workspace", ["Status.LoadingWorkspace"] = "Loading workspace",
        ["Status.ReplayingWorkspace"] = "Replaying workspace ({0}/{1})", ["Status.WorkspaceLoaded"] = "Workspace loaded",
        ["Status.WorkspaceLoadFailed"] = "Workspace load failed",
        ["Session.Count"] = "{0} submissions", ["Session.Memory"] = "{0} submissions — Worker {1:N0} MiB",
        ["Session.StateLost"] = "0 submissions — Worker state lost", ["Session.Restarted"] = "0 submissions — Worker restarted",
        ["Diagnostics.Count"] = "{0} errors, {1} warnings", ["Diagnostics.Unavailable"] = "Diagnostics unavailable", ["Cursor.Position"] = "Ln {0}, Col {1}",
        ["Diagnostics.Deferred"] = "Diagnostics update after execution",
        ["Diagnostics.DeferredDetail"] = "Diagnostics will run after variables and types from the current execution are available.",
        ["Diagnostics.Checking"] = "Checking diagnostics…",
        ["Diagnostics.CheckingDetail"] = "Errors and warnings are checked after typing pauses.",
        ["Diagnostics.NavigateHint"] = "Click or press F8 for next; press Shift+F8 for previous.",
        ["Diagnostics.More"] = "{0:N0} more",
        ["Status.DiagnosticLocation"] = "Diagnostic {0}/{1}: {2} ({3},{4})",
        ["Explorer.Loading"] = "Loading…", ["Explorer.Filtering"] = "Filtering…", ["Explorer.Unavailable"] = "Explorer unavailable",
        ["Explorer.Count"] = "{0:N0} types · {1:N0} methods · {2:N0} enum values", ["Explorer.Matches"] = "{0:N0} matches",
        ["Explorer.MatchesLimited"] = "{0:N0} matches · showing first {1:N0}",
        ["Package.SearchPrompt"] = "Search packages on nuget.org", ["Package.Searching"] = "Searching nuget.org…", ["Package.Cancelled"] = "NuGet operation cancelled.",
        ["Package.NoneFound"] = "No packages found.", ["Package.Found"] = "{0:N0} packages found — showing {1}",
        ["Package.QueryChanged"] = "Search for '{0}' finished. Press Enter to search the current text.",
        ["Package.CriteriaChanged"] = "Search criteria changed. Press Enter to search again.",
        ["Package.Installing"] = "Installing {0} {1}…", ["Package.InstallingLatest"] = "Installing the latest stable {0}…", ["Package.LatestStable"] = "latest stable",
        ["Package.Installed"] = "Installed {0}.", ["Package.InstalledVersion"] = "Installed {0} {1}.",
        ["Package.AlreadyInstalled"] = "{0} {1} is already installed.",
        ["Assist.CompletionHint"] = "Tab: complete  ↑↓: select  PageUp/PageDown: page  Esc: close",
        ["Assist.SignatureHint"] = "{0} overload(s) · parameter {1}/{2}: {3} · ↑↓: switch",
        ["Assist.SignatureHintNoParameter"] = "{0} overload(s) · ↑↓: switch",
        ["Assist.ActiveParameter"] = "Active parameter: {0} {1}",
        ["Assist.NoParameterDocumentation"] = "No documentation is available for this parameter.",
        ["Assist.Documentation"] = "Documentation",
        ["Assist.LoadingDocumentation"] = "Loading documentation…",
        ["Assist.AutoImport"] = "Accepting this completion automatically adds using {0}.",
        ["Assist.NoDocumentation"] = "No documentation is available for this item.",
        ["Assist.DocumentationLanguageHint"] = "Shows documentation authored by the referenced library. Open localized Microsoft Learn from Symbol Explorer when available.",
        ["QuickInfo.Hint"] = "Esc: close · Ctrl+K, Ctrl+I: show again",
        ["Status.QuickInfoChord"] = "Press Ctrl+I to show Quick Info",
        ["Status.QuickInfoShown"] = "Showing Quick Info at the caret",
        ["Status.QuickInfoUnavailable"] = "No Quick Info is available at the caret",
        ["Message.WorkerConnected"] = "Worker connected. Do not execute untrusted code or packages.",
        ["Message.WorkerDisconnected"] = "The Worker disconnected unexpectedly ({0}). Restart the Worker to continue.",
        ["Message.WorkerEventApplyFailed"] = "Could not apply the {0} event to the UI: {1}",
        ["Message.WorkerExitCode"] = "exit code {0}",
        ["Message.WorkerExitDetail"] = "exit code {0}: {1}",
        ["Message.WorkerPipeClosed"] = "the communication channel was closed",
        ["Message.WorkerUnavailable"] = "The Worker is not connected. Restart the Worker first.",
        ["Message.ExecutionCancelled"] = "Execution cancelled.", ["Message.SessionReset"] = "Session reset.",
        ["Message.WorkerRestarted"] = "Worker restarted. Variables and methods were lost; references and usings were restored.",
        ["Message.ForcedRestart"] = "Worker was terminated because cancellation did not complete. Session variables were lost; transcript and input history were preserved.",
        ["Message.SessionBusy"] = "Code is running or another session operation is in progress. Wait for it to finish or stop execution.",
        ["Message.PackageAdded"] = "Package added: {0} {1}", ["Message.UsingAdded"] = "Using added: {0}",
        ["Message.UsingAutoAdded"] = "Automatically added using from completion: {0}",
        ["Message.UsingExecutionAutoAdded"] = "Automatically added using before execution: {0}",
        ["Message.UsingActive"] = "Using already active: {0}", ["Message.ReferenceAdded"] = "Reference added: {0}",
        ["Message.UsingRemoved"] = "Using removed: {0}",
        ["Message.UsingRemovedWithRestart"] = "Worker rebuilt to remove using {0}. Session variables, types, and methods were lost.",
        ["Message.UsingMissing"] = "Using not found: {0}",
        ["Message.NoReferences"] = "No dynamic references.", ["Message.NoPackages"] = "No packages.",
        ["Message.UnknownCommand"] = "Unknown command: {0}",
        ["Message.WorkspaceSaved"] = "Workspace saved: {0}", ["Message.WorkspaceLoaded"] = "Workspace loaded and {0} submissions replayed.",
        ["Message.ReferenceMissing"] = "Reference file was not found and was skipped: {0}", ["Message.ReplayFailed"] = "Submission {0} failed during replay.",
        ["Dialog.WorkspaceLoadTitle"] = "Open Workspace",
        ["Dialog.WorkspaceLoadWarning"] = "The current Worker state will be discarded and saved submissions replayed in order. Side effects such as file operations will run again. Continue?",
        ["Dialog.UsingRemoveTitle"] = "Remove using",
        ["Dialog.UsingRemoveWarning"] = "Removing using {0} requires rebuilding the Worker. Current session variables, types, and methods will be lost; transcript, history, and references are preserved. Continue?",
        ["Dialog.RestartTitle"] = "Restart Worker", ["Dialog.RestartWarning"] = "Restarting the Worker clears current variables, types and methods; transcript, history and references are retained. Continue?",
        ["Dialog.ResetTitle"] = "Reset submission state", ["Dialog.ResetWarning"] = "Clear current variables, types and methods? Added references and usings are retained.",
        ["Dialog.ErrorTitle"] = "PlayGroundSharp Error",
        ["Dialog.WorkspaceFilter"] = "PlayGroundSharp Workspace (*.pgsworkspace)|*.pgsworkspace|JSON (*.json)|*.json",
        ["Dialog.DataFileFilter"] = "All files (*.*)|*.*|JSON (*.json;*.jsonl)|*.json;*.jsonl|Text (*.txt;*.log;*.csv)|*.txt;*.log;*.csv",
        ["Dialog.ResultSaveTitle"] = "Save Result",
        ["Dialog.TranscriptSaveTitle"] = "Save Transcript",
        ["Dialog.TextFileFilter"] = "Text (*.txt)|*.txt|All files (*.*)|*.*",
        ["Dialog.ResultFileFilter"] = "Text (*.txt)|*.txt|JSON (*.json)|*.json|All files (*.*)|*.*",
        ["Help.Title"] = "PlayGroundSharp Help", ["Help.SecurityTitle"] = "Security notice",
        ["Help.SecurityMessage"] = "Submitted C# and added packages run with your current Windows user permissions. Do not run untrusted code or packages.",
        ["About.Message"] = "Stateful C# interactive console\n.NET 10 / WPF / Roslyn\n\nArbitrary code runs with your current Windows user permissions.",
        ["Completion.Command"] = "PlayGroundSharp command",
        ["Completion.Namespace"] = "Namespace from an added assembly; Tab inserts the using command."
    };

    public static IReadOnlyDictionary<string, string> Resources(AppLanguageMode mode) =>
        mode == AppLanguageMode.Japanese ? Japanese : English;

    public static string Text(AppLanguageMode mode, string key, params object?[] arguments)
    {
        var value = Resources(mode).GetValueOrDefault(key) ?? key;
        return arguments.Length == 0 ? value : string.Format(value, arguments);
    }
}
